"""Slice A — hotel setup: hotels, room_types, hotel_policies

Revision ID: 0001
Revises:
Create Date: 2026-08-19

Written by hand rather than autogenerated, because autogenerate needs a
live database to diff against.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY_CATEGORIES = (
    "checkin_checkout",
    "cancellation",
    "pets",
    "payment",
    "other",
)


def upgrade() -> None:
    op.create_table(
        "hotels",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("whatsapp_number", sa.String(length=40), nullable=True),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            server_default="NPR",
        ),
        sa.Column(
            "timezone",
            sa.String(length=64),
            nullable=False,
            server_default="Asia/Kathmandu",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "room_types",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_occupancy", sa.Integer(), nullable=False),
        sa.Column("amenities_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_room_types_hotel_id", "room_types", ["hotel_id"])

    op.create_table(
        "hotel_policies",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(*POLICY_CATEGORIES, name="policy_category"),
            nullable=False,
        ),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_hotel_policies_hotel_id", "hotel_policies", ["hotel_id"])


def downgrade() -> None:
    op.drop_index("ix_hotel_policies_hotel_id", table_name="hotel_policies")
    op.drop_table("hotel_policies")
    op.drop_index("ix_room_types_hotel_id", table_name="room_types")
    op.drop_table("room_types")
    op.drop_table("hotels")
    # Postgres keeps the enum type after the table is gone; drop it so a
    # downgrade/upgrade cycle doesn't fail with "type already exists".
    sa.Enum(name="policy_category").drop(op.get_bind(), checkfirst=True)
