"""Slice B - knowledge base: pgvector, knowledge_documents, knowledge_chunks

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-20

Written by hand rather than autogenerated: autogenerate does not emit
CREATE EXTENSION, and it needs a live database to diff against.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SOURCE_TYPES = ("faq", "policy", "amenity", "upload")

# Must match EMBEDDING_DIM in app/modules/receptionist/models/knowledge.py.
# 384 = sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2.
#
# No ANN index is created. pgvector cannot index beyond 2000 dimensions, and
# at pilot scale (1-2 hotels, hundreds of chunks) an exact sequential scan
# is both fast enough and perfectly accurate. Add HNSW when chunk counts
# make recall/latency an actual problem, not before.
EMBEDDING_DIM = 384


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(*SOURCE_TYPES, name="knowledge_source_type"),
            nullable=False,
        ),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_knowledge_documents_hotel_id", "knowledge_documents", ["hotel_id"]
    )

    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("knowledge_document_id", sa.Integer(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_document_id"],
            ["knowledge_documents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_knowledge_chunks_document_id",
        "knowledge_chunks",
        ["knowledge_document_id"],
    )
    op.create_index("ix_knowledge_chunks_hotel_id", "knowledge_chunks", ["hotel_id"])


def downgrade() -> None:
    op.drop_index("ix_knowledge_chunks_hotel_id", table_name="knowledge_chunks")
    op.drop_index("ix_knowledge_chunks_document_id", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_knowledge_documents_hotel_id", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    sa.Enum(name="knowledge_source_type").drop(op.get_bind(), checkfirst=True)
    # The vector extension is intentionally left installed: dropping it
    # would break any other schema relying on it, and it is harmless.
